<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>37a00cea-6071-426b-a51a-07a0b388de47</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.9" />
    <PackageReference Include="Scalar.AspNetCore" Version="2.16.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Popcorn.Shared\Popcorn.Shared.csproj" />
  </ItemGroup>

</Project>
